# Generated by Django 5.0.6 on 2024-11-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_favorite_num_alter_company_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_num',
        ),
    ]
